name: Install Dependencies
description: This is a composite GitHub Action that sets up pnpm, node and installs the project's dependencies.

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash