version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run: npm run bundlesize

      - run:
          command: npm run start:app
          background: true

      - run: sleep 10

      - run: yarn cypress
