version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn bundlesize
