version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run bundlesize
