name: Feature request
description: Suggest an idea for this project
title: '[Feature request]: '
labels: [feature request, waiting-up-vote]
assignees:
  - bluebill1049
body:
  - type: textarea
    id: decription
    attributes:
      label: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe alternatives you've considered
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/react-hook-form/react-hook-form/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
