name: E2E Test

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
