name: E2E Test

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: pnpm start
          browser: replay-chromium
          wait-on: 'http://ip6-localhost:3000'
          wait-on-timeout: 120
        env:
          RECORD_REPLAY_DISABLE_ASSERTS: 1
      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.7
        with:
          api-key: rwk_GKBZEmNqZ0Ep8hCzL8DtNRGGLFFpkkOYPOeWLmhLyQB
          public: true
