name: E2E Test

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
        with:
          version: ${{ matrix.node-version }}

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: pnpm start
          wait-on: 'http://ip6-localhost:3000'
          wait-on-timeout: 120
