name: Issue Check

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v1.0.0
        id: checkUser
        with:
          require: 'write'

      - name: check invalid
        if: (contains(github.event.issue.body, 'codesandbox.io') == false && contains(github.event.issue.body, 'stackblitz.com') == false) && (steps.checkUser.outputs.result == 'false')
        uses: actions-cool/issues-helper@v1.2
        with:
          actions: 'create-comment,add-labels,close-issue'
          issue-number: ${{ github.event.issue.number }}
          labels: 'status: need more detail'
          body: |
            Hey @${{ github.event.issue.user.login }}, Your issue has been closed due to a lack of minimal information supplied. Please follow the issue template. Thank you!
